### ISSUE TITLE
What is the recommended WeakMap polyfill?

### ISSUE THREAD

**Issue by limonte** [dgraham/delegated-events#18]
As per README:

> Internet Explorer requires polyfills for CustomEvent and WeakMap.

The suggested WeakMap polyfill is archived https://github.com/googlearchive/WeakMap and not installable with npm/yarn.

It should be possible to install that dependency with the repo URL, but is that really what you're suggesting?

**Comment by dgraham** [comment]
That's the implementation we used while supporting IE 9 and 10. IE 11 does not require a polyfill and we stopped using one after dropping support for IE 10.

So I'm not sure which one to recommend now since I haven't used any others in production. If you find one that works well, I can update the link.

**Comment by limonte** [comment]
> That's the implementation we used while supporting IE 9 and 10. IE 11 does not require a polyfill and we stopped using one after dropping support for IE 10.

What about Android 4.4? It doesn't support `WeakMap` as well and according to https://developer.android.com/about/dashboards/ still widely used (8.6%) Do you support it?

**Comment by dgraham** [comment]
Yes, it works on old mobile browsers.

**Comment by limonte** [comment]
[weakmap-polyfill](https://github.com/polygonplanet/weakmap-polyfill) seems to work nicely: https://glitch.com/edit/#!/sand-gallon?path=index.html:9:4

**Comment by robertmirro** [comment]
What about core-js that’s used by [@babel/polyfill](https://github.com/babel/babel/blob/master/packages/babel-polyfill/package.json)?

**Comment by limonte** [comment]
> What about core-js that’s used by @babel/polyfill?

- `weakmap-polyfill` - [763 bytes](https://checkgzipcompression.com/?url=https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fweakmap-polyfill%402.0.0%2Fweakmap-polyfill.min.js)
- `@babel/polyfill` - [31,175 bytes](https://checkgzipcompression.com/?url=https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2F%40babel%2Fpolyfill%407.0.0%2Fbrowser.js)

**Comment by robertmirro** [comment]
@babel/polyfill inclusion was only mentioned to infer quality.  :smile: 

The entire webpack bundle for beta 3 `import weakMap from 'core-js/es/weak-map';` gzips to just over 6k, but I was mainly suggesting [core-js](https://www.npmjs.com/package/core-js) because it's actively maintained with 9.5 million downloads/week and 6700+ stars.
