### ISSUE TITLE
The `on` function does not work with `focus`

### ISSUE THREAD

**Issue by AlanKrygowski** [dgraham/delegated-events#36]
The `on` function does not seem to trigger at all when fired for the `focus` event.
Here's an example of the issue:
https://codepen.io/aln447/pen/zYoEjab

The same listener works well for all the others i've tested including the `focusin` event.

The focus event is the only one I can use in my usecase, and it would be great if it was corrected.
Thanks

**Comment by keithamus** [comment]
Hey @AlanKrygowski thanks for the issue!

[The MDN docs allude to the problem here](https://developer.mozilla.org/en-US/docs/Web/API/Element/focus_event). The `focus` event does not bubble, so cannot have delegate listeners. It must be bound to directly. `focusin` _does_ bubble, however. 

The description of [delegated events in this readme](https://github.com/dgraham/delegated-events#delegated-events) hints that it can only listen to bubbling events.

I'll close this, as there's nothing we can do to fix this. The browsers built in behaviour for the `focus` event (among others) is such that it cannot be delegated.

**Comment by leggleton** [comment]
For the same reason the blur event also does not work. Just adding in case any body happens upon this.
